import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entry: [
    "src/index.ts",
    "src/db/index.ts",
    "src/redis.ts",
    "src/types/index.ts",
    "src/types/settings.ts",
    "src/run-start.ts",
    "src/send-newsletter.ts",
    "src/constants/index.ts",
    "src/scheduling/index.ts",
    "src/utils/index.ts",
    "src/utils/prompt-hash.ts",
    "src/utils/timezone-date.ts",
    "src/utils/reading-time.ts",
    "src/logger.ts",
    "src/slack/index.ts",
    "src/pricing.ts",
    "src/cost.ts",
    "src/services/index.ts",
    "src/services/credential-cipher.ts",
    "src/types/eval-ranking.ts",
    "src/types/eval-ranking-schemas.ts",
    "src/constants/eval-ranking.ts",
    "src/services/url-safety.ts",
    "src/services/static-page-fetcher.ts",
    "src/services/page-metadata.ts",
    "src/services/summary-source.ts",
    "src/review-edits/index.ts",
    "src/alerting/index.ts",
    "src/types/incident.ts",
  ],
  format: ["esm"],
  dts: true,
  clean: !options.watch,
  sourcemap: true,
}));
